# Generated by Django 3.2.11 on 2024-08-26 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_inversión', models.CharField(max_length=100)),
                ('monto_invertido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_actual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('riesgo', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_de_riesgo', models.CharField(max_length=50)),
                ('prioridad_financiera', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_deuda', models.CharField(max_length=100)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_restante', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tasa_de_interés', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_de_vencimiento', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_ahorrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meta_de_ahorro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mes', models.PositiveIntegerField()),
                ('año', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ahorros Mensuales',
                'unique_together': {('user', 'mes', 'año')},
            },
        ),
    ]
